packages:
  - pizzaz_server_node
  - kitchen_sink_server_node
  - cards_against_ai_server_node
  - mcp_app_basics_node
  - ecommerce_server_node

onlyBuiltDependencies:
  - '@modelcontextprotocol/ext-apps'
  - '@tailwindcss/oxide'
  - esbuild
